document.writeln("<div id=\"contact\">");
document.writeln("				<h1>Contact</h1>");
document.writeln("				<ul>");
document.writeln("					<li style=\"width: 30%;\">");
document.writeln("						<a href=\"\"></a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\"https://www.linkedin.com/in/danielantelo/\"><img alt=\"LinkedIn\" src=\"./images/linked.png\" style=\"width: 40%; min-width: 50px;\"></a>");
document.writeln("					</li>");
document.writeln("					<li style=\"width: 0%;\">");
document.writeln("						<a href=\"\"></a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\"mailto:dar1u16@soton.ac.uk\"><img alt=\"LinkedIn\" src=\"./images/emailicon.png\" style=\"width: 50%; min-width: 70px;\"></a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\"\"></a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<div style=\"text-align:center; font-size: 2em; margin-top: 50px;\">    ");
document.writeln("				© 2020 Daniel Antelo");
document.writeln("			</div>");