document.write("<ul class=\"nav\">");
document.write("			<li class=\"header_list_separator\">｜<\/li>");
document.write("			<li><a href=\"index.html\">Home<\/a><\/li>");
document.write("			<li class=\"header_list_separator\">｜<\/li>");
document.write("			<li class=\"dropdown\">");
document.write("                <a href=\"javascript:void(0)\" class=\"dropbtn\">University Projects<\/a>");
document.write("                <div class=\"dropdown-content\">");
document.write("                    <a href=\".\/project_sirius\/project_sirius.html\">Sirius Bipropellant Rocket<\/a>");
document.write("                    <a href=\".\/project_cubesat\/project_cubesat.html\">Scientific CubeSat Concept Study<\/a>");
document.write("                    <a href=\".\/project_ir_radiometer\/project_ir_radiometer.html\">Miniaturised Infrared Radiometer<\/a>");
document.write("                    <a href=\".\/project_uav\/project_uav.html\">Fixed Wing UAV<\/a>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("			<li class=\"header_list_separator\">｜<\/li>");
document.write("			<li class=\"dropdown\">");
document.write("                <a href=\"javascript:void(0)\" class=\"dropbtn\">Personal Projects, Guides & Tutorials<\/a>");
document.write("                <div class=\"dropdown-content\">");
document.write("                    <a href=\".\/project_geiger\/project_geiger.html\">Arduino Geiger-Müller Counter<\/a>");
document.write("					<a href=\".\/project_g5_mod\/project_g5_mod.html\">Power Mac G5 ATX Mod<\/a>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("			<li class=\"header_list_separator\">｜<\/li>");
document.write("		<\/ul>");